# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to practice NumPy and Pandas - Exercises

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development - First Iteration 2023 v.1.0 

# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [2]:
# The code goes here
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [6]:
#Code comes here
arr1 = np.ones((10))
print(arr1)

arr2 = np.arange(1,21,1,dtype="int")
print(arr2)

arr3 = np.ones((5,5))
print(arr3)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [11]:
# Code comes here
arr4 = np.random.randn(3,3,3)
print(arr4)
print(" ")
arr5 = arr4.reshape(27)
print(arr5)

[[[ 1.35224125  1.03246582  0.40532227]
  [ 0.59269894 -0.27053439 -0.70856493]
  [ 1.27901049  1.91514347  2.82559051]]

 [[-0.60557537 -0.03027738  0.25897645]
  [ 0.48229458  0.78092205  0.83959179]
  [-0.6456379  -0.65305134 -0.43303135]]

 [[-0.16570282  1.18992426  0.52730248]
  [-0.38766446 -1.34947094  1.97613722]
  [-0.10192292 -3.49373368  0.00646673]]]
 
[ 1.35224125  1.03246582  0.40532227  0.59269894 -0.27053439 -0.70856493
  1.27901049  1.91514347  2.82559051 -0.60557537 -0.03027738  0.25897645
  0.48229458  0.78092205  0.83959179 -0.6456379  -0.65305134 -0.43303135
 -0.16570282  1.18992426  0.52730248 -0.38766446 -1.34947094  1.97613722
 -0.10192292 -3.49373368  0.00646673]


# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [13]:
# Code comes here
arr6 = np.random.randint(1,10,20)
print(arr6)

[8 9 2 7 6 2 9 9 1 6 6 9 2 2 4 7 2 9 7 8]


## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [16]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)

In [29]:
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
#Code goes here


```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [42]:
# Code come here
print(a[1:5, 3:5])

[[ 9 10]
 [14 15]
 [19 20]
 [24 25]]


```python
array([ 6,  7,  8,  9, 10])
```

In [43]:
# Code comes here
print(a[1])

[ 6  7  8  9 10]


## 2.5 

Calculate the sum of all the numbers in `a`.

In [46]:
# Code comes here
b = sum(a)
c = sum(b)
print(c)

325


## 2.6 

Calculate the sum of each row in `a`.

In [ ]:
# Code comes here


## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [ ]:
# Code comes here

# Practicing Pandas

## 2.8

In this set of practice exercises we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [47]:
# Codes comes here
import pandas as pd

## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [55]:
# Code comes here
Footprint_df = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv")


## 2.10 

How many rows and columns are there in the dataframe?

In [56]:
#Code comes here


1430


## 2.11

What is the mean `co2_emission` of the whole dataset?

In [ ]:
# Code comes here

## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [ ]:
# Code comes here

## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

In [ ]:
#code comes here

## 2.14

Which country consumes the least amount of beef per person per year?


In [ ]:
# code comes here

## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

In [ ]:
# code comes here

# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [ ]:
# code comes here

## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assistance.