# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to practice NumPy and Pandas - Exercises

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development - First Iteration 2023 v.1.0 

# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [1]:
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [2]:
lst1 = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
arr1 = np.array(lst1)
print(type(lst1))
print(type(arr1))
print(arr1)


<class 'list'>
<class 'numpy.ndarray'>
[1 1 1 1 1 1 1 1 1 1]


In [4]:
lst2 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
arr2 = np.array(lst2)
print(type(lst2))
print(type(arr2))
print(arr2)

<class 'list'>
<class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [8]:
import numpy as np

lst3= [[1,1,1,1,1], [1,1,1,1,1], [1,1,1,1,1], [1,1,1,1,1], [1,1,1,1,1]]
arr3 = np. array(lst3, dtype="int")
print(arr3)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [21]:
arr4= np.ones((5,5,))
print(arr4)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [15]:
import numpy as np

arr4= np.random.randn(3, 3, 3)
print(arr4)

[[[-0.9589416  -0.83051577  0.59730433]
  [ 0.60822469  0.10970224 -0.98028164]
  [ 1.40073434 -0.05436812  0.775664  ]]

 [[ 0.38023863  0.36217552 -0.67054609]
  [-1.27320502 -1.21188581 -0.69351361]
  [ 1.19847128 -0.74399207 -1.63311182]]

 [[ 0.28207038 -1.91933349  0.25660137]
  [-0.02616986 -2.03560365  0.93945968]
  [-0.24018713 -0.53874119  0.59206071]]]


# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [25]:
# Code comes here

arr5= np.linspace(1,10,20)
print(arr5)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [3]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
20

In [ ]:
#Code goes here

import numpy as np
print ( 

```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [17]:
# Code come here

array= np.array([6, 7, 8, 9, 10])
print(array)

[ 6  7  8  9 10]


```python
array([ 6,  7,  8,  9, 10])
```

In [ ]:
# Code comes here

## 2.5 

Calculate the sum of all the numbers in `a`.

In [5]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
print(a)
print(1+26)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
27


## 2.6 

Calculate the sum of each row in `a`.

In [7]:
# Code comes here
print(1+26)
print(5+-1)

27
4


## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [8]:
# Code comes here

import numpy as np
a= np.arange([False, True]).reshape([False, False])
print(a)

TypeError: unsupported operand type(s) for -: 'list' and 'int'

# Practicing Pandas

## 2.8

In this set of practice exercises we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [18]:
# Codes comes here

import pandas as pd

## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [10]:
# Code comes here

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv')
df.head


<bound method NDFrame.head of          country             food_category  consumption  co2_emmission
0      Argentina                      Pork        10.51          37.20
1      Argentina                   Poultry        38.66          41.53
2      Argentina                      Beef        55.48        1712.00
3      Argentina               Lamb & Goat         1.56          54.63
4      Argentina                      Fish         4.36           6.96
...          ...                       ...          ...            ...
1425  Bangladesh        Milk - inc. cheese        21.91          31.21
1426  Bangladesh  Wheat and Wheat Products        17.47           3.33
1427  Bangladesh                      Rice       171.73         219.76
1428  Bangladesh                  Soybeans         0.61           0.27
1429  Bangladesh   Nuts inc. Peanut Butter         0.72           1.27

[1430 rows x 4 columns]>

## 2.10 

How many rows and columns are there in the dataframe?

In [ ]:
#Code comes here

1430 rows 
4 columns


## 2.11

What is the mean `co2_emission` of the whole dataset?

In [17]:
# Code comes here

co2_mean = df["co2_emmission"].mean()
print(co2_mean)

74.383993006993


## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [20]:
# Code comes here

co2_max = df["co2_emmission"].max()
print(co2_max)

1712.0


## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

In [57]:
#code comes here

import pandas as pd

foodproduction_prod = df[(df["food_category"]=="Beef") & (df["co2_emmission"]>1000)]
print(foodproduction_prod)
print('')
print(len(foodproduction_prod))
print('')


       country food_category  consumption  co2_emmission
2    Argentina          Beef        55.48        1712.00
13   Australia          Beef        33.86        1044.85
57         USA          Beef        36.24        1118.29
90      Brazil          Beef        39.25        1211.17
123    Bermuda          Beef        33.15        1022.94

5



## 2.14

Which country consumes the least amount of beef per person per year?


In [79]:
# code comes here

beef_df = df.loc[df["food_category"] == "Beef"]
print(beef_df)
beef_min = beef_df.loc[beef_df["consumption"]==beef_df.consumption.min()]
print(beef_min.country)

           country food_category  consumption  co2_emmission
2        Argentina          Beef        55.48        1712.00
13       Australia          Beef        33.86        1044.85
24         Albania          Beef        22.50         694.30
35         Iceland          Beef        13.36         412.26
46     New Zealand          Beef        22.49         693.99
...            ...           ...          ...            ...
1377  Sierra Leone          Beef         1.99          61.41
1388     Sri Lanka          Beef         1.38          42.58
1399     Indonesia          Beef         2.59          79.92
1410       Liberia          Beef         0.78          24.07
1421    Bangladesh          Beef         1.28          39.50

[130 rows x 4 columns]
1410    Liberia
Name: country, dtype: object


## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

In [82]:
# code comes here

allmeat_df = df["food_category"].isin(["Pork", "Poultry", "Fish", "Lamb & Goat", "Beef"])
print(allmeat_df)
meatem= 

0        True
1        True
2        True
3        True
4        True
        ...  
1425    False
1426    False
1427    False
1428    False
1429    False
Name: food_category, Length: 1430, dtype: bool


KeyError: 'co2_emmission'

# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [85]:
nonmeat_df = df["food_category"].isin(["Milk - inc. cheese", "Wheat and Wheat Products", "Rice", "Soybeans", "Nuts inc. Peanut Butter"])
print(nonmeat_df)

totalnonmeat= 


# code comes here

0       False
1       False
2       False
3       False
4       False
        ...  
1425     True
1426     True
1427     True
1428     True
1429     True
Name: food_category, Length: 1430, dtype: bool


## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assistance.